[package]
name = "yappla"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = "0.10.0-beta.4"
glib = { version = "0.21", features = ["v2_74"] }
[profile.release]
opt-level = 3
lto = true
debug = false

